output_dir: /results/counterfactuals/

seg_model:
classifier_model:
  name: "vgg16_bn"      # vgg16   vgg16_bn

concept_layer: features.37    # 29  # 40

intermediate_layers:
  - features.37
  - features.40

attribution_file_path: /results/counterfactuals/data_representation/imagenet_acts_base.h5
analysis_file_path: /results/counterfactuals/data_representation/analysis.h5

cf_attr_file_path: /results/counterfactuals/data_representation/imagenet_acts_cf.h5

data:
  _target_: data.datasets.ImageNet
  root: '/Data/imagenet/val'
  idx_to_tgt_cls_path: './ldce/data/image_idx_to_tgt.yaml'
  split: 'val'
  return_tgt_cls: True
  batch_size: 4
  start_sample: 10
  end_sample: 50

cf_data:
  _target_: data.datasets.ImageNet
  root: '/Data/imagenet/val'
  idx_to_tgt_cls_path: './ldce/data/image_idx_to_tgt.yaml'
  split: 'val'
  return_tgt_cls: True
  batch_size: 4
  start_sample: 0
  end_sample: 10